# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitio', '0002_auto_20160418_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('birth', models.DateTimeField()),
                ('email', models.CharField(blank=True, max_length=50)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.Gender')),
                ('group', models.ManyToManyField(blank=True, to='sitio.Group')),
                ('idType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.UserType')),
                ('profilePic', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Picture')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='idType',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profilePic',
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userauth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
