# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_auto_20160528_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
