# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 04:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitio', '0004_auto_20160528_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='event',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='allConfirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sitio.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='waiting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.Group'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
