# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_auto_20160530_0454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='user',
            new_name='userAuth',
        ),
    ]
