# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_auto_20160429_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='userauth',
            new_name='userAuth',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Picture'),
        ),
    ]
