# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0006_auto_20160530_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='meeting',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='sitio.Meeting'),
            preserve_default=False,
        ),
    ]
