# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_auto_20160606_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='allConfirmed',
        ),
    ]
