# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_remove_group_allconfirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='allConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
