# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0010_group_allconfirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Picture'),
        ),
    ]
