# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='name',
            field=models.CharField(default='Lugar', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(blank=True, to='sitio.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Picture'),
        ),
    ]
