# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='content',
            field=models.TextField(default='Probando', max_length=1000),
            preserve_default=False,
        ),
    ]
