# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_thread_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='thread',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.Thread'),
            preserve_default=False,
        ),
    ]
