# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_reply_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='submit_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='submit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
